using System;
using System.IO;
using System.Text;

using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Args;
using Telegram.Bot.Extensions.Polling;
using Telegram.Bot.Exceptions;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types.InputFiles;

namespace ServerTransfer_bot // Note: actual namespace depends on the project name.
{
    class Program
    {
        #region global Property and variable

        // guid that generated by bot_father bot in telegram. 
        static private string? BotGuid;
        // bot client that connect to telegram server.
        static TelegramBotClient? botClient;
        // every update from user interact
        static Update mUpdate;
        static CancellationTokenSource Cts = new CancellationTokenSource();
        static CancellationToken canceltoken;

        #endregion

        #region Main(Start)

        static FileExplorer fx =new FileExplorer();

        static void Main(string[] args)
        {
            Console.WriteLine(fx.CurrentPath);

            // check for guid(token) exist in file or not.
            guidChecker();

            botClient = new TelegramBotClient(BotGuid);

            // StartReceiving does not block the caller thread. Receiving is done on the ThreadPool.
            var receiverOptions = new ReceiverOptions
            {
                AllowedUpdates = { } // receive all update types
            };

            // start bot 
            botClient.StartReceiving(
                HandleUpdateAsync,
                HandleErrorAsync,
                receiverOptions,
                cancellationToken: Cts.Token);

            Console.WriteLine("Running ...");
            Console.ReadKey();
        }// End of main

        #endregion

        #region Update Handling

        static async Task HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
        {
            mUpdate = update;
            canceltoken = cancellationToken;

            // Only process Message updates: https://core.telegram.org/bots/api#message
            if (update.Type != UpdateType.Message)
                return;
            else
            {
                // Only process text messages
                if (update.Message!.Type == MessageType.Text)
                {
                    var chatId = update.Message.Chat.Id;
                    var messageText = update.Message.Text;

                    Console.WriteLine($"Received a '{messageText}' message in chat {chatId}.");

                    CommandHandler(messageText);
                }

                //Only process documents(mostly all kind of file pdf,exe,txt,zip and ...)
                else if (update.Message!.Type == MessageType.Document)
                {
                    var chatIdf = update.Message.Chat.Id;

                    Message sentMessagef = await botClient.SendTextMessageAsync(
                    chatId: chatIdf,
                    text: "You send:\n" + update.Message.Document.FileName + " - " +
                        update.Message.Document.MimeType + " - " + "File",
                    cancellationToken: cancellationToken);

                    FileDownloader(update.Message.Document.FileName, update.Message.Document.FileId);
                }
            }
        }// end of Handle Update Async

        #endregion

        #region CommandHandling

        static void CommandHandler(string command)
        {
            if (command == "/start")
            {
                SendMessage("Welcome to File Transfer Robot");
            }
            else if (command == "/getfile")
            {
                SendMessage("Getting File is Under Maintenance ...");
            }
            else if (command == "/sendfile")
            {
                SendMessage("Sending File is Under Maintenance ...");
            }
            else if (command == "/explore")
            {
                SendMessage("File Exploration is Under Maintenance ...");
            }
            else
            {
                SendMessage("Use Proper Command");
            }
        }// end of CommandHandling

        /// <summary>
        /// send message to user
        /// </summary>
        /// <param name="message">text of message</param>
        static async void SendMessage(string message)
        {
            Int64 ChatId = mUpdate.Message.Chat.Id;

            Message SentMessage = await botClient.SendTextMessageAsync(
                chatId : ChatId,
                text : message,
                cancellationToken: canceltoken);
        }

        #endregion

        #region File Downloader

        /// <summary>
        /// download file that user send to bot in server side
        /// </summary>
        /// <param name="FileName">name of file that user send</param>
        /// <param name="FileId">a string that telegram give to each file uploaded to telegram server</param>
        static async void FileDownloader(string FileName,string FileId)
        {
            try
            {
                //Get file info from telegram server
                Telegram.Bot.Types.File file = await botClient.GetFileAsync(FileId);

                // downloaded file from telegram server and stream(save) it to file
                FileStream fs = new FileStream(FileName, FileMode.Create);

                // downloading file
                await botClient.DownloadFileAsync(file.FilePath, fs);

                //flush fileStream process.
                fs.Close();
                fs.Dispose();
            }
            catch (Exception e)
            {
                ErrorLog(e.Message);
            }
            
        }// end of FileDownloader.

        #endregion

        #region ErrorHandling and check

        static Task HandleErrorAsync(ITelegramBotClient botClient, Exception exception, CancellationToken cancellationToken)
        {
            var ErrorMessage = exception switch
            {
                ApiRequestException apiRequestException
                    => $"Telegram API Error:\n[{apiRequestException.ErrorCode}]\n{apiRequestException.Message}",
                _ => exception.ToString()
            };

            //Console.WriteLine(ErrorMessage);
            ErrorLog(ErrorMessage);
            return Task.CompletedTask;
        }

        /// <summary>
        /// check if guid file exit or not. if not exist make one and get guid from user.
        /// </summary>
        static void guidChecker()
        {
            if (System.IO.File.Exists("guid.txt"))
            {
                // read guid from text file.
                BotGuid = System.IO.File.ReadAllText("guid.txt");
            }
            else
            {
                // take guid from user and write it in text file.
                Console.WriteLine("Enter guid :");
                string? s = Console.ReadLine();
                BotGuid = s;
                System.IO.File.WriteAllText("guid.txt", s);
            }
        } // end of guidChacker

        /// <summary>
        /// log all error into a file.
        /// </summary>
        /// <param name="str">error string</param>
        static void ErrorLog(string str)
        {
            System.IO.File.AppendAllText("log.txt", str + DateTime.Now);
        }

        #endregion


    }// End of Program Class
}// End of MyApp namespace
